CREATE SCHEMA dv_rsa;
GRANT USAGE ON SCHEMA dv_rsa TO PUBLIC;

CREATE TABLE dv_rsa.conversor (
RSA_USERID VARCHAR,
DOCUMENTO VARCHAR,
TIPODOCUMENTO VARCHAR,
GRUPO VARCHAR,
PORTAL VARCHAR,
NOMBRE VARCHAR,
PRIMERLOGIN DATE,
ULTIMOLOGIN DATE,
CONSTRAINT pk_conv PRIMARY KEY (RSA_USERID)
); 

\copy dv_rsa.conversor FROM '/projects/conversor/DatosConversor.csv' DELIMITER ',' CSV HEADER;
ANALYZE dv_rsa.conversor;
